# Site
title: Cyberhelp
subtitle: for Researchers & Teams
email: cyberhelp@sesync.org
copyright: |
  &copy; National Socio-Environmental Synthesis Center (SESYNC)<br>
  1 Park Place, Suite 300, Annapolis, MD 21401

# Content
collections:
  category:
    output: true
    permalink: /:title/
  tag:
    output: true
    permalink: /:collection/:title/
plugins:
  - jemoji
  - jekyll-feed

# Build
repository: SESYNC-ci/sesync-ci.github.io
exclude:
  - README.md
  - CONTRIBUTING.md
  - CNAME
  - Gemfile.lock
  - Gemfile
  - "*.Rproj*"
  - "*.Rmd"
theme: jekyll-theme-leap-day
sass:
  sass_dir: ./assets/css
defaults:
  - scope:
      path: ""
      type: category
    values:
      layout: category
  - scope:
      path: ""
      type: tag
    values:
      toc: true
      layout: tag
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      sticky: false
      permalink: /:categories/:title.html
