# Site
title: Cyberhelp
subtitle: for Researchers & Teams
email: cyberhelp@sesync.org
copyright: |
  &copy; National Socio-Environmental Synthesis Center (SESYNC)<br>
  1 Park Place, Suite 300, Annapolis, MD 21401

# Content
plugins:
  - jemoji
  - jekyll-feed
sass:
  sass_dir: ./assets/css

# Build
repository: SESYNC-ci/sesync-ci.github.io
exclude:
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - scripts/
  - cache/
  - .Rproj.user/
  - "*.Rproj*"
  - "*.Rmd"
theme: jekyll-theme-leap-day
defaults:
  - scope:
      path: "*/index.md"
      type: pages
    values:
      layout: category
  - scope:
      path: "/lesson/*"
      type: posts
    values:
      permalink: "/:slug"
  - scope:
      path: ""
      type: posts
    values:
      toc: true
      sticky: false
      permalink: /:categories/:title.html